name: doc-deployment
on: [push, pull_request]
jobs:
  pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Install Rust (rustup)
      run: rustup update stable --no-self-update && rustup default stable

    - name: Build book
      run: |
        cargo install mdbook
        mdbook build
        touch book/.nojekyll
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      if: github.event_name == 'push' && github.repository == 'fortran-fans/mdbook-test' && ( startsWith( github.ref, 'refs/tags/' ) || github.ref == 'refs/heads/main' )
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: book
        CLEAN: true